<?xml version="1.0" encoding="ASCII"?>
<!--
  Copyright (c) 2005 The Apache Software Foundation or its licensors, as applicable.

  Licensed under the Apache License, Version 2.0 (the "License");
  you may not use this file except in compliance with the License.
  You may obtain a copy of the License at

     http://www.apache.org/licenses/LICENSE-2.0

  Unless required by applicable law or agreed to in writing, software
  distributed under the License is distributed on an "AS IS" BASIS,
  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  See the License for the specific language governing permissions and
  limitations under the License.
 -->
<module xmlns="http://www.osoa.org/xmlns/sca/0.9" xmlns:v="http://www.osoa.org/xmlns/sca/values/0.9"
        name="bigbank.account">
        
	<import.sdo factory="com.bigbank.account.AccountFactory" />
	<import.sdo factory="net.x.webservice.WebserviceFactory" />
    
    <import.wsdl wsdlLocation="wsdl/AccountService.wsdl"/>
    <!-- import.wsdl wsdlLocation="wsdl/StockQuoteWebService.wsdl"/ -->
    <import.wsdl wsdlLocation="wsdl/stockquotes.webservicex.wsdl"/>

    <entryPoint name="AccountService">
        <interface.java interface="com.bigbank.account.AccountService"/>
        <binding.ws port="http://www.bigbank.com/account#wsdl.endpoint(AccountService/AccountServiceSOAP)"/>
        <reference>AccountServiceComponent/AccountService</reference>
    </entryPoint>

    <component name="AccountServiceComponent">
        <implementation.java class="bigbank.account.services.account.AccountServiceImpl"/>
        <properties>
            <v:currency>EURO</v:currency>
        </properties>
        <references>
            <v:accountDataService>AccountDataServiceComponent</v:accountDataService>
            <v:stockQuoteService>StockQuoteServiceComponent</v:stockQuoteService>
        </references>
    </component>

    <component name="AccountDataServiceComponent">
        <implementation.java class="bigbank.account.services.accountdata.AccountDataServiceDASImpl"/>
    </component>

	<!-- Local -->
    <component name="StockQuoteServiceComponent">
        <implementation.java class="bigbank.account.services.stockquote.StockQuoteServiceImpl"/>
    </component>
   
   <!-- WebServiceX Web Service -->
    <externalService name="StockQuoteWebService">
        <interface.wsdl interface="http://www.webserviceX.NET/#wsdl.interface(StockQuoteSoap)"/>
        <binding.ws port="http://www.webserviceX.NET/#wsdl.endpoint(StockQuote/StockQuoteSoap)"/>
    </externalService>

</module>