<?xml version="1.0" encoding="UTF-8"?>
<!--
  Copyright (c) 2005 The Apache Software Foundation or its licensors, as applicable.

  Licensed under the Apache License, Version 2.0 (the "License");
  you may not use this file except in compliance with the License.
  You may obtain a copy of the License at

     http://www.apache.org/licenses/LICENSE-2.0

  Unless required by applicable law or agreed to in writing, software
  distributed under the License is distributed on an "AS IS" BASIS,
  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  See the License for the specific language governing permissions and
  limitations under the License.
 -->
<module xmlns="http://www.osoa.org/xmlns/sca/0.9" xmlns:v="http://www.osoa.org/xmlns/sca/values/0.9"
        name="interop.client">

    <import.sdo factory="org.soapinterop.SoapinteropFactory"/>
    <import.wsdl location="wsdl/interopdoc.wsdl" namespace="http://soapinterop.org/"/>

    <component name="LoopbackInteropDocServiceComponent">
        <implementation.java class="org.apache.tuscany.test.interop.client.LoopbackInteropDocServiceComponentImpl"/>
    </component>
    
    <externalService name="RemoteInteropDocService">
        <interface.wsdl interface="http://soapinterop.org/#DocTestPortType"/>
        <binding.ws port="http://soapinterop.org/#interopDocPort"/>
    </externalService>
    
    <externalService name="LocalHostInteropDocService">
        <interface.wsdl interface="http://soapinterop.org/#DocTestPortType"/>
        <binding.ws uri="http://localhost:8080/tuscany-testing-interop-server-SNAPSHOT/services/InteropDocService"
          port="http://soapinterop.org/#interopDocPort"/>
    </externalService>
    
</module>
