/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package calculator.android;

public final class R {
    public static final class attr {
    }
    public static final class drawable {
        public static final int icon=0x7f020000;
    }
    public static final class layout {
        public static final int main=0x7f030000;
    }
    public static final class raw {
        public static final int calculator_composite=0x7f040000;
        public static final int sca=0x7f040001;
        public static final int sca_all=0x7f040002;
        public static final int sca_binding_ejb=0x7f040003;
        public static final int sca_binding_jms=0x7f040004;
        public static final int sca_binding_sca=0x7f040005;
        public static final int sca_binding_webservice=0x7f040006;
        public static final int sca_core=0x7f040007;
        public static final int sca_definitions=0x7f040008;
        public static final int sca_implementation_bpel=0x7f040009;
        public static final int sca_implementation_composite_xsd=0x7f04000a;
        public static final int sca_implementation_cpp=0x7f04000b;
        public static final int sca_implementation_ejb=0x7f04000c;
        public static final int sca_implementation_java=0x7f04000d;
        public static final int sca_implementation_spring=0x7f04000e;
        public static final int sca_interface_cpp=0x7f04000f;
        public static final int sca_interface_java=0x7f040010;
        public static final int sca_interface_wsdl=0x7f040011;
        public static final int sca_policy=0x7f040012;
        public static final int tuscany_sca=0x7f040013;
        public static final int tuscany_sca_binding_atom=0x7f040014;
        public static final int tuscany_sca_binding_dwr=0x7f040015;
        public static final int tuscany_sca_binding_http=0x7f040016;
        public static final int tuscany_sca_binding_jsonrpc=0x7f040017;
        public static final int tuscany_sca_binding_notification=0x7f040018;
        public static final int tuscany_sca_binding_rmi=0x7f040019;
        public static final int tuscany_sca_binding_rss=0x7f04001a;
        public static final int tuscany_sca_implementation_node=0x7f04001b;
        public static final int tuscany_sca_implementation_notification=0x7f04001c;
        public static final int tuscany_sca_implementation_osgi=0x7f04001d;
        public static final int tuscany_sca_implementation_resource=0x7f04001e;
        public static final int tuscany_sca_implementation_script=0x7f04001f;
        public static final int tuscany_sca_implementation_widget=0x7f040020;
        public static final int tuscany_sca_implementation_xquery=0x7f040021;
    }
    public static final class string {
        public static final int app_name=0x7f050000;
    }
}
